package com.lewys.arcade.util;

import org.bukkit.ChatColor;

public class C
{
  public static String scramble = "§k";
  public static String bold = "§l";
  public static String strike = "§m";
  public static String line = "\n";
  public static String reset = "§r";
  public static String Italics = "§o";
  public static String cAqua = "§b";
  public static String cBlack = "§0";
  public static String cBlue = "§9";
  public static String cDAqua = "§3";
  public static String cDBlue = "§1";
  public static String cDGray = "§8";
  public static String cDGreen = "§2";
  public static String cDPurple = "§5";
  public static String cDRed = "§4";
  public static String cGold = "§6";
  public static String cGray = "§7";
  public static String cGreen = "§a";
  public static String cPurple = "§d";
  public static String cRed = "§c";
  public static String cWhite = "§f";
  public static String cYellow = "§e";
  public static String mHead = "§9";
  public static String mBody = "§7";
  public static String mChat = "§f";
  public static String mElem = "§e";
  public static String mCount = "§e";
  public static String mTime = "§a";
  public static String mItem = "§e";
  public static String mSkill = "§a";
  public static String mLink = "§a";
  public static String mLoot = "§c";
  public static String mGame = "§d";
  public static String wField = "§f";
  public static String wFrame = "§8";
  public static String descHead = "§2";
  public static String descBody = "§f";
  public static String chatPMHead = "§2";
  public static String chatPMBody = "§a";
  public static String chatClanHead = "§3";
  public static String chatClanBody = "§b";
  public static String chatAdminHead = "§5";
  public static String chatAdminBody = "§d";
  public static String listTitle = "§f";
  public static String listValue = "§e";
  public static String listValueOn = "§a";
  public static String listValueOff = "§c";
  public static String rAll = "§f";
  public static String rHelp = "§d";
  public static String rMod = "§a";
  public static String rAdmin = "§4";
  public static String rOwner = "§5";
  public static String consoleHead = "§c";
  public static String consoleFill = "§f";
  public static String consoleBody = "§e";
  public static String sysHead = "§8";
  public static String sysBody = "§7";
  public static String chat = "§f";
  public static ChatColor xBorderlands = ChatColor.GOLD;
  public static ChatColor xWilderness = ChatColor.YELLOW;
  public static ChatColor xMid = ChatColor.WHITE;
  public static ChatColor xNone = ChatColor.GRAY;
  public static ChatColor xAdmin = ChatColor.WHITE;
  public static ChatColor xSafe = ChatColor.AQUA;
  public static ChatColor xSelf = ChatColor.AQUA;
  public static ChatColor xAlly = ChatColor.GREEN;
  public static ChatColor xEnemy = ChatColor.YELLOW;
  public static ChatColor xWar = ChatColor.RED;
  public static ChatColor xPillage = ChatColor.LIGHT_PURPLE;
  public static ChatColor xdSelf = ChatColor.DARK_AQUA;
  public static ChatColor xdAlly = ChatColor.DARK_GREEN;
  public static ChatColor xdEnemy = ChatColor.GOLD;
  public static ChatColor xdWar = ChatColor.DARK_RED;
  public static ChatColor xdPillage = ChatColor.DARK_PURPLE;
}

